In [3]:
import pandas as pd
import numpy as np

# Création du DataFrame
df = {
    'Duration': [
        60, 60, 60, 45, 45, 60, 60, 450, 30, 60,
        60, 60, 60, 60, 60, 60, 60, 60, 45, 60,
        45, 60, 45, 60, 45, 60, 60, 60, 60, 60,
        60, 60
    ],
    'Date': [
        '2020/12/01', '2020/12/02', '2020/12/03', '2020/12/04', '2020/12/05',
        '2020/12/06', '2020/12/07', '2020/12/08', '2020/12/09', '2020/12/10',
        '2020/12/11', '2020/12/12', '2020/12/12', '2020/12/13', '2020/12/14',
        '2020/12/15', '2020/12/16', '2020/12/17', '2020/12/18', '2020/12/19',
        '2020/12/20', '2020/12/21', np.nan, '2020/12/23', '2020/12/24',
        '2020/12/25', '2020/12/26', '2020/12/27', '2020/12/28', '2020/12/29',
        '2020/12/30', '2020/12/31'
    ],
    'Pulse': [
        110, 117, 103, 109, 117, 102, 110, 104, 109, 98,
        103, 100, 100, 106, 104, 98, 98, 100, 90, 103,
        97, 108, 100, 130, 105, 102, 100, 92, 103, 100,
        102, 92
    ],
    'Maxpulse': [
        130, 145, 135, 175, 148, 127, 136, 134, 133, 124,
        147, 120, 120, 128, 132, 123, 120, 120, 112, 123,
        125, 131, 119, 101, 132, 126, 120, 118, 132, 132,
        129, 115
    ],
    'Calories': [
        409.1, 479.0, 340.0, 282.4, 406.0, 300.0, 374.0, 253.3, 195.1, 269.0,
        329.3, 250.7, 250.7, 345.3, 379.3, 275.0, 215.2, 300.0, np.nan, 323.0,
        243.0, 364.2, 282.0, 300.0, 246.0, 334.5, 250.0, 241.0, np.nan, 280.0,
        380.3, 243.0
    ]
}

# Création du DataFrame
df = pd.DataFrame(df)

# Affichage du DataFrame
print(df)

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112       NaN
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         NaN    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132       NaN
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

In [4]:
## Suprimer les lignes  avec des champs sans valeurs (NaN)
df1 = df.dropna()
print(df1)

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

In [8]:
## Remplacer  les valeurs nulles 
x = df["Calories"].mean()
df["Calories"].fillna(x, inplace= True)
print(df)

    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130    409.10
1         60  2020/12/02    117       145    479.00
2         60  2020/12/03    103       135    340.00
3         45  2020/12/04    109       175    282.40
4         45  2020/12/05    117       148    406.00
5         60  2020/12/06    102       127    300.00
6         60  2020/12/07    110       136    374.00
7        450  2020/12/08    104       134    253.30
8         30  2020/12/09    109       133    195.10
9         60  2020/12/10     98       124    269.00
10        60  2020/12/11    103       147    329.30
11        60  2020/12/12    100       120    250.70
12        60  2020/12/12    100       120    250.70
13        60  2020/12/13    106       128    345.30
14        60  2020/12/14    104       132    379.30
15        60  2020/12/15     98       123    275.00
16        60  2020/12/16     98       120    215.20
17        60  2020/12/17    100       120    300.00
18        45  2020/12/18     90       112    304.68
19        60  2020/12/19    103       123    323.00
20        45  2020/12/20     97       125    243.00
21        60  2020/12/21    108       131    364.20
22        45         NaN    100       119    282.00
23        60  2020/12/23    130       101    300.00
24        45  2020/12/24    105       132    246.00
25        60  2020/12/25    102       126    334.50
26        60  2020/12/26    100       120    250.00
27        60  2020/12/27     92       118    241.00
28        60  2020/12/28    103       132    304.68
29        60  2020/12/29    100       132    280.00
30        60  2020/12/30    102       129    380.30
31        60  2020/12/31     92       115    243.00

In [11]:
## Convert To time
df["Date"] = pd.to_datetime(df["Date"])
print(df["Date"])

0    2020-12-01
1    2020-12-02
2    2020-12-03
3    2020-12-04
4    2020-12-05
5    2020-12-06
6    2020-12-07
7    2020-12-08
8    2020-12-09
9    2020-12-10
10   2020-12-11
11   2020-12-12
12   2020-12-12
13   2020-12-13
14   2020-12-14
15   2020-12-15
16   2020-12-16
17   2020-12-17
18   2020-12-18
19   2020-12-19
20   2020-12-20
21   2020-12-21
22          NaT
23   2020-12-23
24   2020-12-24
25   2020-12-25
26   2020-12-26
27   2020-12-27
28   2020-12-28
29   2020-12-29
30   2020-12-30
31   2020-12-31
Name: Date, dtype: datetime64[ns]

In [12]:
df.describe()

,Duration,Date,Pulse,Maxpulse,Calories
count,32.000000,31,32.000000,32.000000,32.000000
mean,68.437500,2020-12-15 16:15:29.032258048,103.500000,128.500000,304.680000
min,30.000000,2020-12-01 00:00:00,90.000000,101.000000,195.100000
25%,60.000000,2020-12-08 12:00:00,100.000000,120.000000,250.700000
50%,60.000000,2020-12-15 00:00:00,102.500000,127.500000,300.000000
75%,60.000000,2020-12-23 12:00:00,106.500000,132.250000,341.325000
max,450.000000,2020-12-31 00:00:00,130.000000,175.000000,479.000000
std,70.039591,NaN,7.832933,12.998759,63.839129